
# Resume configs:

full_name: Saman Nezafat
title: Saman Nezafat
# description: Python Backend Developer

pdf: true
pdf_url: https://github.com/onionj/cv/raw/gh-pages/cv.pdf

github: true
github_url: https://github.com/onionj

linkedin: true
linkedin_url: https://www.linkedin.com/in/samannzft/

gmail: true
gmail_url: samannzft@gmail.com

phone: false
phone_number: ""

footer: false
site_footer_text: ""

# creater pdf configs:

URL: https://onionj.github.io/cv/

# template configs:

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: "en-US"